INSERT INTO sector (name) VALUES
                            ('Agriculture & Natural Resources'),
                            ('Construction & Property'),
                            ('Manufacturing'),
                            ('Retail & E-commerce'),
                            ('Hospitality & Food'),
                            ('Transport & Logistics'),
                            ('Technology'),
                            ('Finance & Insurance'),
                            ('Healthcare & Social Care'),
                            ('Education & Training'),
                            ('Professional Services'),
                            ('Marketing & Creative'),
                            ('Media & Entertainment'),
                            ('Beauty & Personal Care'),
                            ('Sports & Fitness'),
                            ('Automotive'),
                            ('Home & Property Services'),
                            ('Energy & Utilities'),
                            ('Science & Pharmaceuticals'),
                            ('Government & Public Services'),
                            ('Charity & Non-Profit'),
                            ('Travel & Tourism'),
                            ('Other');
